import type { Miniature } from "./types";

export const MOCK_MINIATURES: Miniature[] = [
  {
    id: '1',
    name: 'The Witcher - Yennefer of Vengerberg',
    imagePath: 'https://ibb.co/rf798Ws4',
    tags: ['#Ведьмак', '#Йенифер', '#Девушки', '#Фигурки'],
    fileSize: '1 гб',
    compressedSize: '560 мб',
    cost: '20 рублей',
    resinConsumption: '100 грамм',
    dateAdded: '15.01.2026',
    dateEdited: '15.01.2026',
  },
    {
    id: '2',
    name: 'The Witcher - Geralt of Rivia',
    imagePath: 'https://placehold.co/150x200/262626/FFF?text=Geralt',
    tags: ['#Ведьмак', '#Геральт', '#Мужчины', '#Фигурки'],
    fileSize: '1.1 ГБ',
    compressedSize: '490 МБ',
    cost: '15 ₽',
    resinConsumption: '120 г',
    dateAdded: '16.01.2026',
    dateEdited: '16.01.2026',
  },
    {
    id: '3',
    name: 'Dark Souls - Knight Artorias',
    imagePath: 'https://placehold.co/150x200/262626/FFF?text=Artorias',
    tags: ['#DarkSouls', '#Арториас', '#Рыцари', '#Фигурки'],
    fileSize: '2.1 ГБ',
    compressedSize: '890 МБ',
    cost: '35 ₽',
    resinConsumption: '180 г',
    dateAdded: '18.01.2026',
    dateEdited: '19.01.2026',
  },
];